
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Frame frame1;
	
	private global::Gtk.Alignment GtkAlignment;
	
	private global::Gtk.Table table1;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.Button connectButton;
	
	private global::Gtk.ComboBox baudRateComboBox;
	
	private global::Gtk.Label baudRateLabel;
	
	private global::Gtk.Label portLabel;
	
	private global::Gtk.ComboBox portsComboBox;
	
	private global::Gtk.Label GtkLabel1;
	
	private global::Gtk.Frame frame2;
	
	private global::Gtk.Alignment GtkAlignment1;
	
	private global::Gtk.Table table2;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.HScale pwmPinSlider10;
	
	private global::Gtk.HScale pwmPinSlider11;
	
	private global::Gtk.HScale pwmPinSlider3;
	
	private global::Gtk.HScale pwmPinSlider5;
	
	private global::Gtk.HScale pwmPinSlider6;
	
	private global::Gtk.HScale pwmPinSlider9;
	
	private global::Gtk.Entry pwmValue10;
	
	private global::Gtk.Entry pwmValue11;
	
	private global::Gtk.Entry pwmValue3;
	
	private global::Gtk.Entry pwmValue5;
	
	private global::Gtk.Entry pwmValue6;
	
	private global::Gtk.Entry pwmValue9;
	
	private global::Gtk.ToggleButton togglebuttonPin10;
	
	private global::Gtk.ToggleButton togglebuttonPin11;
	
	private global::Gtk.ToggleButton togglebuttonPin12;
	
	private global::Gtk.ToggleButton togglebuttonPin13;
	
	private global::Gtk.ToggleButton togglebuttonPin2;
	
	private global::Gtk.ToggleButton togglebuttonPin3;
	
	private global::Gtk.ToggleButton togglebuttonPin4;
	
	private global::Gtk.ToggleButton togglebuttonPin5;
	
	private global::Gtk.ToggleButton togglebuttonPin6;
	
	private global::Gtk.ToggleButton togglebuttonPin7;
	
	private global::Gtk.ToggleButton togglebuttonPin8;
	
	private global::Gtk.ToggleButton togglebuttonPin9;
	
	private global::Gtk.Label GtkLabel14;
	
	private global::Gtk.Statusbar statusbar1;
	
	private global::Gtk.Entry statusCommandEntry;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("SerialTest");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
		this.frame1.BorderWidth = ((uint)(3));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(9));
		// Container child table1.Gtk.Table+TableChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.alignment1.LeftPadding = ((uint)(196));
		// Container child alignment1.Gtk.Container+ContainerChild
		this.connectButton = new global::Gtk.Button ();
		this.connectButton.CanFocus = true;
		this.connectButton.Name = "connectButton";
		this.connectButton.UseStock = true;
		this.connectButton.UseUnderline = true;
		this.connectButton.Label = "gtk-connect";
		this.alignment1.Add (this.connectButton);
		this.table1.Add (this.alignment1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.alignment1]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.baudRateComboBox = global::Gtk.ComboBox.NewText ();
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("300"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("600"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("1200"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("2400"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("9600"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("14400"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("19200"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("38400"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("57600"));
		this.baudRateComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("115200"));
		this.baudRateComboBox.Name = "baudRateComboBox";
		this.table1.Add (this.baudRateComboBox);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.baudRateComboBox]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.baudRateLabel = new global::Gtk.Label ();
		this.baudRateLabel.Name = "baudRateLabel";
		this.baudRateLabel.Xalign = 1F;
		this.baudRateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Baud:");
		this.baudRateLabel.Justify = ((global::Gtk.Justification)(1));
		this.table1.Add (this.baudRateLabel);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.baudRateLabel]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.portLabel = new global::Gtk.Label ();
		this.portLabel.Name = "portLabel";
		this.portLabel.Xalign = 1F;
		this.portLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Port:");
		this.portLabel.Justify = ((global::Gtk.Justification)(1));
		this.table1.Add (this.portLabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.portLabel]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.portsComboBox = global::Gtk.ComboBox.NewText ();
		this.portsComboBox.Name = "portsComboBox";
		this.table1.Add (this.portsComboBox);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.portsComboBox]));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel1 = new global::Gtk.Label ();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Connection Settings</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel1;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(10));
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(5));
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(12)), ((uint)(4)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 02");
		this.table2.Add (this.label1);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 11");
		this.table2.Add (this.label10);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
		w12.TopAttach = ((uint)(9));
		w12.BottomAttach = ((uint)(10));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 12");
		this.table2.Add (this.label11);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
		w13.TopAttach = ((uint)(10));
		w13.BottomAttach = ((uint)(11));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 13");
		this.table2.Add (this.label12);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
		w14.TopAttach = ((uint)(11));
		w14.BottomAttach = ((uint)(12));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 03");
		this.table2.Add (this.label2);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 04");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 05");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 06");
		this.table2.Add (this.label5);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
		w18.TopAttach = ((uint)(4));
		w18.BottomAttach = ((uint)(5));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 07");
		this.table2.Add (this.label6);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
		w19.TopAttach = ((uint)(5));
		w19.BottomAttach = ((uint)(6));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 08");
		this.table2.Add (this.label7);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
		w20.TopAttach = ((uint)(6));
		w20.BottomAttach = ((uint)(7));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 09");
		this.table2.Add (this.label8);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
		w21.TopAttach = ((uint)(7));
		w21.BottomAttach = ((uint)(8));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("PIN 10");
		this.table2.Add (this.label9);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
		w22.TopAttach = ((uint)(8));
		w22.BottomAttach = ((uint)(9));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider10 = new global::Gtk.HScale (null);
		this.pwmPinSlider10.CanFocus = true;
		this.pwmPinSlider10.Name = "pwmPinSlider10";
		this.pwmPinSlider10.Adjustment.Upper = 255;
		this.pwmPinSlider10.Adjustment.PageIncrement = 10;
		this.pwmPinSlider10.Adjustment.StepIncrement = 1;
		this.pwmPinSlider10.DrawValue = true;
		this.pwmPinSlider10.Digits = 0;
		this.pwmPinSlider10.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider10);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider10]));
		w23.TopAttach = ((uint)(8));
		w23.BottomAttach = ((uint)(9));
		w23.LeftAttach = ((uint)(2));
		w23.RightAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider11 = new global::Gtk.HScale (null);
		this.pwmPinSlider11.CanFocus = true;
		this.pwmPinSlider11.Name = "pwmPinSlider11";
		this.pwmPinSlider11.Adjustment.Upper = 255;
		this.pwmPinSlider11.Adjustment.PageIncrement = 10;
		this.pwmPinSlider11.Adjustment.StepIncrement = 1;
		this.pwmPinSlider11.DrawValue = true;
		this.pwmPinSlider11.Digits = 0;
		this.pwmPinSlider11.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider11);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider11]));
		w24.TopAttach = ((uint)(9));
		w24.BottomAttach = ((uint)(10));
		w24.LeftAttach = ((uint)(2));
		w24.RightAttach = ((uint)(3));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider3 = new global::Gtk.HScale (null);
		this.pwmPinSlider3.CanFocus = true;
		this.pwmPinSlider3.Name = "pwmPinSlider3";
		this.pwmPinSlider3.Adjustment.Upper = 255;
		this.pwmPinSlider3.Adjustment.PageIncrement = 10;
		this.pwmPinSlider3.Adjustment.StepIncrement = 1;
		this.pwmPinSlider3.DrawValue = true;
		this.pwmPinSlider3.Digits = 0;
		this.pwmPinSlider3.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider3);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider3]));
		w25.TopAttach = ((uint)(1));
		w25.BottomAttach = ((uint)(2));
		w25.LeftAttach = ((uint)(2));
		w25.RightAttach = ((uint)(3));
		w25.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider5 = new global::Gtk.HScale (null);
		this.pwmPinSlider5.CanFocus = true;
		this.pwmPinSlider5.Name = "pwmPinSlider5";
		this.pwmPinSlider5.Adjustment.Upper = 255;
		this.pwmPinSlider5.Adjustment.PageIncrement = 10;
		this.pwmPinSlider5.Adjustment.StepIncrement = 1;
		this.pwmPinSlider5.DrawValue = true;
		this.pwmPinSlider5.Digits = 0;
		this.pwmPinSlider5.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider5);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider5]));
		w26.TopAttach = ((uint)(3));
		w26.BottomAttach = ((uint)(4));
		w26.LeftAttach = ((uint)(2));
		w26.RightAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider6 = new global::Gtk.HScale (null);
		this.pwmPinSlider6.CanFocus = true;
		this.pwmPinSlider6.Name = "pwmPinSlider6";
		this.pwmPinSlider6.Adjustment.Upper = 255;
		this.pwmPinSlider6.Adjustment.PageIncrement = 10;
		this.pwmPinSlider6.Adjustment.StepIncrement = 1;
		this.pwmPinSlider6.DrawValue = true;
		this.pwmPinSlider6.Digits = 0;
		this.pwmPinSlider6.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider6);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider6]));
		w27.TopAttach = ((uint)(4));
		w27.BottomAttach = ((uint)(5));
		w27.LeftAttach = ((uint)(2));
		w27.RightAttach = ((uint)(3));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmPinSlider9 = new global::Gtk.HScale (null);
		this.pwmPinSlider9.CanFocus = true;
		this.pwmPinSlider9.Name = "pwmPinSlider9";
		this.pwmPinSlider9.Adjustment.Upper = 255;
		this.pwmPinSlider9.Adjustment.PageIncrement = 10;
		this.pwmPinSlider9.Adjustment.StepIncrement = 1;
		this.pwmPinSlider9.DrawValue = true;
		this.pwmPinSlider9.Digits = 0;
		this.pwmPinSlider9.ValuePos = ((global::Gtk.PositionType)(2));
		this.table2.Add (this.pwmPinSlider9);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmPinSlider9]));
		w28.TopAttach = ((uint)(7));
		w28.BottomAttach = ((uint)(8));
		w28.LeftAttach = ((uint)(2));
		w28.RightAttach = ((uint)(3));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue10 = new global::Gtk.Entry ();
		this.pwmValue10.CanFocus = true;
		this.pwmValue10.Name = "pwmValue10";
		this.pwmValue10.IsEditable = true;
		this.pwmValue10.InvisibleChar = '•';
		this.table2.Add (this.pwmValue10);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue10]));
		w29.TopAttach = ((uint)(8));
		w29.BottomAttach = ((uint)(9));
		w29.LeftAttach = ((uint)(3));
		w29.RightAttach = ((uint)(4));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue11 = new global::Gtk.Entry ();
		this.pwmValue11.CanFocus = true;
		this.pwmValue11.Name = "pwmValue11";
		this.pwmValue11.IsEditable = true;
		this.pwmValue11.InvisibleChar = '•';
		this.table2.Add (this.pwmValue11);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue11]));
		w30.TopAttach = ((uint)(9));
		w30.BottomAttach = ((uint)(10));
		w30.LeftAttach = ((uint)(3));
		w30.RightAttach = ((uint)(4));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue3 = new global::Gtk.Entry ();
		this.pwmValue3.CanFocus = true;
		this.pwmValue3.Name = "pwmValue3";
		this.pwmValue3.IsEditable = true;
		this.pwmValue3.MaxLength = 3;
		this.pwmValue3.InvisibleChar = '•';
		this.table2.Add (this.pwmValue3);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue3]));
		w31.TopAttach = ((uint)(1));
		w31.BottomAttach = ((uint)(2));
		w31.LeftAttach = ((uint)(3));
		w31.RightAttach = ((uint)(4));
		w31.XOptions = ((global::Gtk.AttachOptions)(0));
		w31.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue5 = new global::Gtk.Entry ();
		this.pwmValue5.CanFocus = true;
		this.pwmValue5.Name = "pwmValue5";
		this.pwmValue5.IsEditable = true;
		this.pwmValue5.InvisibleChar = '•';
		this.table2.Add (this.pwmValue5);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue5]));
		w32.TopAttach = ((uint)(3));
		w32.BottomAttach = ((uint)(4));
		w32.LeftAttach = ((uint)(3));
		w32.RightAttach = ((uint)(4));
		w32.XOptions = ((global::Gtk.AttachOptions)(0));
		w32.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue6 = new global::Gtk.Entry ();
		this.pwmValue6.CanFocus = true;
		this.pwmValue6.Name = "pwmValue6";
		this.pwmValue6.IsEditable = true;
		this.pwmValue6.InvisibleChar = '•';
		this.table2.Add (this.pwmValue6);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue6]));
		w33.TopAttach = ((uint)(4));
		w33.BottomAttach = ((uint)(5));
		w33.LeftAttach = ((uint)(3));
		w33.RightAttach = ((uint)(4));
		w33.XOptions = ((global::Gtk.AttachOptions)(0));
		w33.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.pwmValue9 = new global::Gtk.Entry ();
		this.pwmValue9.CanFocus = true;
		this.pwmValue9.Name = "pwmValue9";
		this.pwmValue9.IsEditable = true;
		this.pwmValue9.InvisibleChar = '•';
		this.table2.Add (this.pwmValue9);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.pwmValue9]));
		w34.TopAttach = ((uint)(7));
		w34.BottomAttach = ((uint)(8));
		w34.LeftAttach = ((uint)(3));
		w34.RightAttach = ((uint)(4));
		w34.XOptions = ((global::Gtk.AttachOptions)(0));
		w34.YOptions = ((global::Gtk.AttachOptions)(0));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin10 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin10.CanFocus = true;
		this.togglebuttonPin10.Name = "togglebuttonPin10";
		this.togglebuttonPin10.UseUnderline = true;
		this.togglebuttonPin10.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w35 = new global::Gtk.Image ();
		w35.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin10.Image = w35;
		this.table2.Add (this.togglebuttonPin10);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin10]));
		w36.TopAttach = ((uint)(8));
		w36.BottomAttach = ((uint)(9));
		w36.LeftAttach = ((uint)(1));
		w36.RightAttach = ((uint)(2));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin11 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin11.CanFocus = true;
		this.togglebuttonPin11.Name = "togglebuttonPin11";
		this.togglebuttonPin11.UseUnderline = true;
		this.togglebuttonPin11.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w37 = new global::Gtk.Image ();
		w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin11.Image = w37;
		this.table2.Add (this.togglebuttonPin11);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin11]));
		w38.TopAttach = ((uint)(9));
		w38.BottomAttach = ((uint)(10));
		w38.LeftAttach = ((uint)(1));
		w38.RightAttach = ((uint)(2));
		w38.XOptions = ((global::Gtk.AttachOptions)(4));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin12 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin12.CanFocus = true;
		this.togglebuttonPin12.Name = "togglebuttonPin12";
		this.togglebuttonPin12.UseUnderline = true;
		this.togglebuttonPin12.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w39 = new global::Gtk.Image ();
		w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin12.Image = w39;
		this.table2.Add (this.togglebuttonPin12);
		global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin12]));
		w40.TopAttach = ((uint)(10));
		w40.BottomAttach = ((uint)(11));
		w40.LeftAttach = ((uint)(1));
		w40.RightAttach = ((uint)(2));
		w40.XOptions = ((global::Gtk.AttachOptions)(4));
		w40.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin13 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin13.CanFocus = true;
		this.togglebuttonPin13.Name = "togglebuttonPin13";
		this.togglebuttonPin13.UseUnderline = true;
		this.togglebuttonPin13.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w41 = new global::Gtk.Image ();
		w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin13.Image = w41;
		this.table2.Add (this.togglebuttonPin13);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin13]));
		w42.TopAttach = ((uint)(11));
		w42.BottomAttach = ((uint)(12));
		w42.LeftAttach = ((uint)(1));
		w42.RightAttach = ((uint)(2));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin2 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin2.CanFocus = true;
		this.togglebuttonPin2.Name = "togglebuttonPin2";
		this.togglebuttonPin2.UseUnderline = true;
		this.togglebuttonPin2.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w43 = new global::Gtk.Image ();
		w43.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin2.Image = w43;
		this.table2.Add (this.togglebuttonPin2);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin2]));
		w44.LeftAttach = ((uint)(1));
		w44.RightAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin3 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin3.CanFocus = true;
		this.togglebuttonPin3.Name = "togglebuttonPin3";
		this.togglebuttonPin3.UseUnderline = true;
		this.togglebuttonPin3.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w45 = new global::Gtk.Image ();
		w45.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin3.Image = w45;
		this.table2.Add (this.togglebuttonPin3);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin3]));
		w46.TopAttach = ((uint)(1));
		w46.BottomAttach = ((uint)(2));
		w46.LeftAttach = ((uint)(1));
		w46.RightAttach = ((uint)(2));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin4 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin4.CanFocus = true;
		this.togglebuttonPin4.Name = "togglebuttonPin4";
		this.togglebuttonPin4.UseUnderline = true;
		this.togglebuttonPin4.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w47 = new global::Gtk.Image ();
		w47.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin4.Image = w47;
		this.table2.Add (this.togglebuttonPin4);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin4]));
		w48.TopAttach = ((uint)(2));
		w48.BottomAttach = ((uint)(3));
		w48.LeftAttach = ((uint)(1));
		w48.RightAttach = ((uint)(2));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin5 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin5.CanFocus = true;
		this.togglebuttonPin5.Name = "togglebuttonPin5";
		this.togglebuttonPin5.UseUnderline = true;
		this.togglebuttonPin5.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w49 = new global::Gtk.Image ();
		w49.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin5.Image = w49;
		this.table2.Add (this.togglebuttonPin5);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin5]));
		w50.TopAttach = ((uint)(3));
		w50.BottomAttach = ((uint)(4));
		w50.LeftAttach = ((uint)(1));
		w50.RightAttach = ((uint)(2));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin6 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin6.CanFocus = true;
		this.togglebuttonPin6.Name = "togglebuttonPin6";
		this.togglebuttonPin6.UseUnderline = true;
		this.togglebuttonPin6.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w51 = new global::Gtk.Image ();
		w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin6.Image = w51;
		this.table2.Add (this.togglebuttonPin6);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin6]));
		w52.TopAttach = ((uint)(4));
		w52.BottomAttach = ((uint)(5));
		w52.LeftAttach = ((uint)(1));
		w52.RightAttach = ((uint)(2));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin7 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin7.CanFocus = true;
		this.togglebuttonPin7.Name = "togglebuttonPin7";
		this.togglebuttonPin7.UseUnderline = true;
		this.togglebuttonPin7.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w53 = new global::Gtk.Image ();
		w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin7.Image = w53;
		this.table2.Add (this.togglebuttonPin7);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin7]));
		w54.TopAttach = ((uint)(5));
		w54.BottomAttach = ((uint)(6));
		w54.LeftAttach = ((uint)(1));
		w54.RightAttach = ((uint)(2));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin8 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin8.CanFocus = true;
		this.togglebuttonPin8.Name = "togglebuttonPin8";
		this.togglebuttonPin8.UseUnderline = true;
		this.togglebuttonPin8.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w55 = new global::Gtk.Image ();
		w55.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin8.Image = w55;
		this.table2.Add (this.togglebuttonPin8);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin8]));
		w56.TopAttach = ((uint)(6));
		w56.BottomAttach = ((uint)(7));
		w56.LeftAttach = ((uint)(1));
		w56.RightAttach = ((uint)(2));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.togglebuttonPin9 = new global::Gtk.ToggleButton ();
		this.togglebuttonPin9.CanFocus = true;
		this.togglebuttonPin9.Name = "togglebuttonPin9";
		this.togglebuttonPin9.UseUnderline = true;
		this.togglebuttonPin9.Label = global::Mono.Unix.Catalog.GetString ("OFF");
		global::Gtk.Image w57 = new global::Gtk.Image ();
		w57.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
		this.togglebuttonPin9.Image = w57;
		this.table2.Add (this.togglebuttonPin9);
		global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table2 [this.togglebuttonPin9]));
		w58.TopAttach = ((uint)(7));
		w58.BottomAttach = ((uint)(8));
		w58.LeftAttach = ((uint)(1));
		w58.RightAttach = ((uint)(2));
		w58.XOptions = ((global::Gtk.AttachOptions)(4));
		w58.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add (this.table2);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel14 = new global::Gtk.Label ();
		this.GtkLabel14.Name = "GtkLabel14";
		this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Control</b>");
		this.GtkLabel14.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel14;
		this.vbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame2]));
		w61.Position = 1;
		w61.Expand = false;
		w61.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Homogeneous = true;
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.statusCommandEntry = new global::Gtk.Entry ();
		this.statusCommandEntry.CanFocus = true;
		this.statusCommandEntry.Name = "statusCommandEntry";
		this.statusCommandEntry.IsEditable = false;
		this.statusCommandEntry.InvisibleChar = '•';
		this.statusbar1.Add (this.statusCommandEntry);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.statusbar1 [this.statusCommandEntry]));
		w62.Position = 1;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w63.Position = 2;
		w63.Expand = false;
		w63.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 512;
		this.DefaultHeight = 718;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.portsComboBox.Changed += new global::System.EventHandler (this.OnPortsComboBoxChanged);
		this.connectButton.Clicked += new global::System.EventHandler (this.OnConnectButtonClicked);
		this.togglebuttonPin9.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin8.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin7.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin6.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin5.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin4.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin3.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin2.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin13.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin12.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin11.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.togglebuttonPin10.Toggled += new global::System.EventHandler (this.OnToggleButtonPinToggled);
		this.pwmValue9.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmValue6.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmValue5.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmValue3.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmValue11.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmValue10.Changed += new global::System.EventHandler (this.OnPwmEntryValueChanged);
		this.pwmPinSlider9.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
		this.pwmPinSlider6.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
		this.pwmPinSlider5.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
		this.pwmPinSlider3.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
		this.pwmPinSlider11.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
		this.pwmPinSlider10.ValueChanged += new global::System.EventHandler (this.OnPwmPinSlider3ValueChanged);
	}
}
